site_name: A320 Documentation
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: blue
    accent: indigo
extra_css:
  - assets/custom.css
extra:
  font:
    text: Roboto
    code: Fira Code
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Systems Overview: systems-overview.md
  - Procedures: procedures.md
  - Tips & Tricks: tips.md
