site_name: A320 Documentation
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: indigo
extra_css:
  - assets/custom.css
extra:
  font:
    text: Roboto
    code: Fira Code
nav:
  - Home: index.md
  - Systems:
      - Electrical: systems/electrical.md
      - Hydraulics: systems/hydraulics.md
  - Procedures:
      - Normal Ops: procedures/normal-ops.md
      - Abnormal Ops: procedures/abnormal-ops.md
